version: '2'

volumes:
  esdata1:
    driver: local
networks: {stack: {}}

services:
    backend:
        extends:
            file: docker-common.yml
            service: django
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 9000
        ports:
            - 9000:9000
            - 3500:3500
        networks: ['stack']
        stdin_open: true
   